### ISSUE TITLE
Exception: Division by zero

### ISSUE THREAD

**Issue by Ewout1988** [rega-cev/rega-genotype#16]
When I download and try to run the HIV typing tool from scratch, I get the following error:

Exception in thread "Thread-19" java.lang.ArithmeticException: / by zero
    at rega.genotype.PhyloClusterAnalysis.retrieveClusterSupports(PhyloClusterAnalysis.java:518)
    at rega.genotype.PhyloClusterAnalysis.compute(PhyloClusterAnalysis.java:626)
    at rega.genotype.PhyloClusterAnalysis.run(PhyloClusterAnalysis.java:869)
    at rega.genotype.PhyloClusterAnalysis.run(PhyloClusterAnalysis.java:44)
    at rega.genotype.AbstractAnalysis.run(AbstractAnalysis.java:193)
    at rega.genotype.PhyloClusterAnalysis.run(PhyloClusterAnalysis.java:888)
    at rega.genotype.viruses.hiv.HIV1SubtypeTool.analyze(HIV1SubtypeTool.java:96)
    at rega.genotype.viruses.hiv.HIVTool.analyze(HIVTool.java:59)
    at rega.genotype.GenotypeTool.analyze(GenotypeTool.java:164)
    at rega.genotype.GenotypeTool.analyze(GenotypeTool.java:131)
    at rega.genotype.ui.viruses.hiv.HivDefinition.startAnalysis(HivDefinition.java:47)
    at rega.genotype.ui.forms.StartForm$5.run(StartForm.java:237)
    at java.lang.Thread.run(Thread.java:745)
parsing ended sequence count = 0

It's solved by changing

`if (!finds1.isEmpty()) {`
to
`if (!finds1.isEmpty() && finds2.size()!=0) {`
on line 518 in PhyloClusterAnalysis.java

And it seems to be that the result is correct. But it has to be further tested to be sure.

**Comment by vagnerfonseca** [comment]
hey Ewout, 

What version of PAUP you are using? I had this same problem, I solved updating the PAUP.
