### ISSUE TITLE
Genotype tool fails on CSV output

### ISSUE THREAD

**Issue by sdwfrost** [rega-cev/rega-genotype#6]
Running the following in the root directory works (for norovirus);

```
java -jar ./dist/rega-genotype-cli-tool-alpha.jar NoV xml test.fas test.xml
```

However, csv output runs, but throws an error at the very end:

```
java -jar ./dist/rega-genotype-cli-tool-alpha.jar NoV csv test.fas test.csv
```

```
REGA_GENOTYPE_CONF_DIR:/Users/sdf22/Programs/rega-genotype/rega-genotype/etc
Loading config file: /Users/sdf22/Programs/rega-genotype/rega-genotype/etc/global-conf.xml
Exception in thread "main" java.lang.NullPointerException
    at rega.genotype.ui.viruses.generic.GenericDefinition.<init>(GenericDefinition.java:86)
    at rega.genotype.GenotypeTool.main(GenotypeTool.java:376)
```

I'm also struggling trying to get the SELF analyses working; the command runs, quits, with no output and no error.

**Comment by Ewout1988** [comment]
I've put an explanation on your previous issue:
https://github.com/rega-cev/rega-genotype/issues/7#issuecomment-197333838
which also applies here. We haven't upgraded NoV to the generic tool yet (due to the complexity of the virus).

For NoV it'll be better (for now, until we add support for NoV to the GenotypeTool) if you replace:
`GenotypeTool genotypeTool = new GenericTool(organism, new File(parseArgsResult.workingDir));` on line 349 in the class GenotypeTool (https://github.com/rega-cev/rega-genotype/blob/master/rega-genotype/src/main/java/rega/genotype/GenotypeTool.java) with
`GenotypeTool genotypeTool = new NoVTool(new File(parseArgsResult.workingDir));`

I think that the reason why the CSV export crashes will also be because of the fact that we haven't upgraded NoV to the GenericTool yet and that it misses some files. It is something that we need to add to the code.
What you could do in the meantime is replace
`GenericDefinition genericDefinition = new GenericDefinition(organism);` on line 276 in the class GenotypeTool with
`NovDefinition genericDefinition = new NovDefinition();`

We could think of adding code to catch the typing for HIV, NoV and ETV as they won't work in the (current version of the) GenotypeTool and will only cause confusion.

I hope this helped

**Comment by sdwfrost** [comment]
Thanks! What do I have to import into GenotypeTool to get the hack to work?

**Comment by Ewout1988** [comment]
I think you'd need those two:
`import rega.genotype.ui.viruses.nov.NovDefinition;`
`import rega.genotype.viruses.nov.NoVTool;`

**Comment by tuliodna** [comment]
Hi Simon

Please let us know what are you interested. It looks that you want to
install locally the Noravirus tool, is that correct?

We have still some unpublished tools, which should be used with care.
Please let us know what are your plans for the tool :)

Warm regards
Tulio

**Comment by sdwfrost** [comment]
Thanks @Ewout1988 , I thought so, but ant can't find them during the build process (which surprised me, as norovirus is one of the organisms in the test suite). I removed some of the excludes from build.xml, but I'm still not getting it to compile. That being said, I don't have a lot of experience in Java, as I prefer C++ for the speed-sensitive stuff, and R/Python for everything else.

@tuliodna We're doing a lot of norovirus stuff right now, and the Noronet webserver freezes such that I can't run large jobs. I'd also like a bit of customisation too (e.g. ORF3 typing, swapping out tree building etc.). I have some Python code that does more or less the same thing, barring the phylotype analysis.

**Comment by kdeforche** [comment]
Hey Simon,

On Wed, Mar 16, 2016 at 4:09 PM, Simon Frost notifications@github.com
wrote:

> Thanks @Ewout1988 https://github.com/Ewout1988 , I thought so, but ant
> can't find them during the build process (which surprised me, as norovirus
> is one of the organisms in the test suite). I removed some of the excludes
> from build.xml, but I'm still not getting it to compile. That being said, I
> don't have a lot of experience in Java, as I prefer C++ for the
> speed-sensitive stuff, and R/Python for everything else.
> 
> @tuliodna https://github.com/tuliodna We're doing a lot of norovirus
> stuff right now, and the Noronet webserver freezes such that I can't run
> large jobs. I'd also like a bit of customisation too (e.g. ORF3 typing,
> swapping out tree building etc.). I have some Python code that does more or
> less the same thing, barring the phylotype analysis.
> 
> I believe you've been communicating with Annelies or Harry, who already
> raised the issue with me -- it seems that the user-interface freezes to
> display the result, although I believe the computation itself will finish.
> If you'll submit the job, then I will be able to return you the result when
> it finishes (directly from the server).

The typing tool git repository is currently unstable as we are doing alot
of architectural changes, so I wouldn't recommend trying to get things to
run using the git version at the moment.

Regards,
Koen

**Comment by sdwfrost** [comment]
Dear @kdeforche 

Thanks, I've just set two files running:

http://www.rivm.nl/mpf/norovirus/typingtool/job/788772105/
http://www.rivm.nl/mpf/norovirus/typingtool/job/1142679796/

It would be good in the medium term if there was an Ant build file for the norovirus typing, so I don't have to bug you!

**Comment by kdeforche** [comment]
Hey Simon,

Oops, I was too late to grab the results from the server. Apparently they
get deleted after 1 month, these days.
Is it possible to resubmit the jobs? I'll monitor them more closely now.

Sorry for the inconvenience.

Koen

**Comment by sdwfrost** [comment]
New runs here:

[http://www.rivm.nl/mpf/norovirus/typingtool/job/2128512743/](http://www.rivm.nl/mpf/norovirus/typingtool/job/2128512743/)
[http://www.rivm.nl/mpf/norovirus/typingtool/job/474145285/](http://www.rivm.nl/mpf/norovirus/typingtool/job/474145285/)

I also noted that the reference files in this repository don't match those on the online version. Is it possible to make them consistent?
